### ISSUE TITLE
No events recorded

### ISSUE THREAD

**Issue by terzano** [olsh/serilog-sinks-sentry#5] opened 2018-01-07 21:44 UTC
I setup as instructed with my DSN on a ASP.NET Core 2.0 project but no log events are sent to Sentry.io. Are there any tricks I should be aware of?

**Comment by olsh** [comment] 2018-01-08 01:20
Hi,
Are there any events in other sinks? 
Try to use the sink without HTTP context capturing (just for tests). 
Try to enable and check debug logs https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics. 
Please note, that only events with level error or higher are logged.

**Comment by terzano** [comment] 2018-01-08 01:36
Thanks for the response. 
Yes, I have a File sink and it is writing properly.  I created a simple project with no other dependencies and still nothing. I am doing log.Error(...) just to try it but nothing is being sent. Fiddle doesn't show any traffic to sentry.io

2018-01-07 20:29:21.504 -05:00 [ERR] Sentry Error Log
System.Exception: Testing Error to Sentry

**Comment by olsh** [comment] 2018-01-08 02:07
Could you please show your startup.cs file with the sink configuration (without your credentials of course)?

**Comment by terzano** [comment] 2018-01-08 05:17
Nothing too special I am afraid, a clean project for testing.
I believe the issue is with the Target Framework. The SharpRaven dependency doesn't support .NET Core, only 4.6.1 

` public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;

            var log = new LoggerConfiguration()
                    .Enrich.FromLogContext()
                    .WriteTo.File("app.log")
                    .WriteTo.Sentry("My DSN")
                    .Destructure.With<HttpContextDestructingPolicy>()
                    .Filter.ByExcluding(e => e.Exception?.CheckIfCaptured() == true)
                    .CreateLogger();

            Log.Logger = log;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.AddSentryContext();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}/{id?}");
            });

            Log.Error(new Exception("Testing Error to Sentry"), "Sentry Error Log");
        }
    }`


`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Serilog" Version="2.6.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Sentry" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Sentry.AspNetCore" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>
</Project>`

**Comment by olsh** [comment] 2018-01-08 08:42
I can't test your code right now, but I have two suggestions
* try to log in a controller action
* try to remove app.AddSentryConext()

I can look into the issue more detail in two days.
The sink was tested with Core 2.0.

**Comment by danielmahadi** [comment] 2018-01-09 15:16
Hi @olsh ,

I also encounter the same issue. I have a log also in the console, and I can see the log in the console.
Here is the setup for serilog that i use
```
var logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
        .WriteTo.Sentry("https://xxx:yyy@sentry.io/123456")
        .WriteTo.Console()       
        .Enrich.FromLogContext()
        .CreateLogger();

      services.AddSingleton<ILogger>(logger);
```

**Comment by olsh** [comment] 2018-01-09 16:01
@terzano you didn't specify destructing policy as described here:
https://github.com/olsh/serilog-sinks-sentry#capturing-httpcontext-aspnet-core

Replace `.Destructure.With()` with `.Destructure.With<HttpContextDestructingPolicy>()`

Hi @danielmahadi 
Please share how you call logging.

**Comment by danielmahadi** [comment] 2018-01-09 20:15
Hi @olsh 

Here is how i call the logging.
```
using Serilog;

private readonly ILogger _logger;
public SimpleController(ILogger logger)
{
    _logger = logger ?? throw new ArgumentNullException(nameof(logger));
}

public IActionResult Get()
{
    try
    {
      //.. code that generate db error
    }
    catch(Exception ex)
    {
      _logger.Error(ex, ex.Message);
    }
}
```

I cannot see anything wrong here, but please help me :)

**Comment by olsh** [comment] 2018-01-09 22:33
@danielmahadi 

The logging code is correct.

Are you capturing HttpContext (have you added `app.AddSentryContext();` to `Configure` method)? If yes, you should add destructing policy and custom filter as described here
https://github.com/olsh/serilog-sinks-sentry#capturing-httpcontext-aspnet-core

**Comment by danielmahadi** [comment] 2018-01-10 07:53
Hi @olsh 

I am not capturing HttpContext

**Comment by danielmahadi** [comment] 2018-01-10 17:26
Hi @olsh 

I managed to find out issue. It is because missing SharpRaven dll. Seems that this is required and I must have missed this.

**Comment by olsh** [comment] 2018-01-10 17:54
Hi @danielmahadi,

Thanks for the info! How did you install the sink?

**Comment by danielmahadi** [comment] 2018-01-10 17:55
Hi @olsh 

I installed this from nuget, funny that the dependency is not included.

**Comment by olsh** [comment] 2018-01-10 17:58
Strange, it has the dependency, you can see this on the page.
https://www.nuget.org/packages/Serilog.Sinks.Sentry/

**Comment by danielmahadi** [comment] 2018-01-10 18:02
Hi @olsh 

Ok I just confirm again. The dependency is not downloaded. Btw, I am using Jetbrains Rider nuget management tool. It should not make different. 

Can you reproduce this with Jetbrains Rider for Mac? or Visual Studio?

**Comment by olsh** [comment] 2018-01-10 18:10
Thank for letting me know.
I can't reproduce this with VS2017, will try with Rider later.

**Comment by danielmahadi** [comment] 2018-01-10 18:15
I think it has to do with the dependency setting in the nuget itself :)

**Comment by olsh** [comment] 2018-01-16 20:41
Hi @danielmahadi 

I managed to reproduce the issue.
It turns out that when a project targets Core 2.x and you install full NET framework library you have to install all dependencies of the library explicitly.
At this moment my only suggestion is to add the dependencies explicitly.

When [the issue](https://github.com/getsentry/raven-csharp/issues/125) will be resolved, I'll add NET Standard target to the projects.

**Comment by danielmahadi** [comment] 2018-01-18 15:45
Hi @olsh,

Good finding. :)

Thanks for this wonder library and keep up the good job.

**Comment by olsh** [comment] 2018-02-03 09:32
Thanks to @dxetech we now have some demo apps.
If someone hit the issue, please check [the demos](https://github.com/olsh/serilog-sinks-sentry/tree/master/demos).

**Comment by olsh** [comment] 2018-03-04 12:51
Version 2.1.2 was build agains net standard 2.0.
So all dependencies will be installed automatically.

Feel free to reopen the issue if you have any problems.

**Closed by olsh** 2018-03-04 12:51 UTC

**Comment by mo-esmp** [comment] 2018-05-19 08:19
Hi @olsh, is there anyway to log events with other log levels ?  other than error level.

**Comment by olsh** [comment] 2018-05-19 12:03
Hi @mo-esmp, sure, you can use `restrictedToMinimumLevel` parameter.

**Comment by mo-esmp** [comment] 2018-05-20 09:37
tnx @olsh. I put my log configuration in `appsettings.json`. is it correct ?
```
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Information",
        "Orleans": "Information"
      }
    },
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "Sentry",
        "Args": {
          "dsn": "dsn",
         "restrictedToMinimumLevel": "Information" // Is This correct ?
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  }

```

**Comment by olsh** [comment] 2018-05-20 14:51
Personally, I configure logging with code, not config files.
The configuration looks valid, but I cannot guarantee that it's 100% correct.
