### ISSUE TITLE
Raven Async support

### ISSUE THREAD

**Issue by sashatk** [olsh/serilog-sinks-sentry#15] opened 2018-10-15 13:56 UTC
Hello, 

could you please add asynchronous sending messaging into Sentry?
Because RavenClient supports  **async** **_ravenClient.CaptureAsync(sentryEvent)_** 
And now your code only support synchronous sending _ravenClient.Capture(sentryEvent);_
Would be nice to have  different Extension methods that support current synchronous operation and asynchronous: e.g . _loggerConfiguration.SentryAsync(sentryConfig.Dns, ... )_

Thank you!

**Comment by chromigo** [comment] 2018-10-19 18:02
As a workaround I use https://github.com/serilog/serilog-sinks-async. But yes it will be nice to have async sink.

**Comment by chromigo** [comment] 2018-10-19 18:05
#9 could be connected with this one

**Comment by max-lancaster** [comment] 2018-11-16 20:16
@sashatk I am using this package together with [serilog-sinks-async](https://github.com/serilog/serilog-sinks-async) which automatically makes all logging calls asynchronous using the standard serilog interface.

**Comment by olsh** [comment] 2019-04-04 09:43
Duplicate of #9

**Closed by olsh** 2019-04-04 09:43 UTC
Labels: duplicate
